version: "3.8"

services:
  customer_order_service:
    image: postgres
    container_name: db_customer_order_service_challange
    restart: always
    networks:
      customer_order_service:
        aliases:
          - database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_customer_order_service
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - customer_order_service
    ports:
      - "5050:80"
    env_file:
      - .env
    networks:
      - customer_order_service
    restart: unless-stopped

volumes:
  dbdata:
  cache:
    driver: local

networks:
  customer_order_service:
    driver: bridge